import { digestText, stableStringify } from '../core/stateDigest'
import { DAYS_PER_MONTH, DAYS_PER_YEAR, MONTHS_PER_YEAR } from '../core/timeEngine'
import type { GameState } from '../types/game'
import type { DebugLogEntry, GameSession, LegacyDebugLogEntryV1, LegacyGameSessionV1, LegacyGameSessionV2, LegacyLifeRecordV1, LegacyLifeRecordV2, LegacyPersistentGameV1, LifeRecord, NormalizedPersistentGameV2, PersistentGame, TransitionalPersistentGameV2, TransitionalPersistentGameV3 } from '../types/persistence'

function cloneCurrentDebugLog(entries: readonly DebugLogEntry[]): DebugLogEntry[] { return entries.map((entry) => ({ ...entry, command: { ...entry.command }, effectTypes: [...entry.effectTypes] })) }
function convertLegacyDebugLog(entries: readonly LegacyDebugLogEntryV1[]): DebugLogEntry[] { return entries.map((entry) => ({ seq: entry.seq, command: { ...entry.command }, worldDayBefore: entry.timeMonthsBefore * DAYS_PER_MONTH, worldDayAfter: entry.timeMonthsAfter * DAYS_PER_MONTH, eventIdBefore: entry.eventIdBefore, eventIdAfter: entry.eventIdAfter, rngBefore: entry.rngBefore, rngAfter: entry.rngAfter, effectTypes: [...entry.effectTypes], stateDigestBefore: entry.stateDigestBefore, stateDigestAfter: entry.stateDigestAfter })) }
function cloneChronicle(entries: GameState['chronicle'] | undefined): GameState['chronicle'] { if (!Array.isArray(entries)) return []; return entries.map((entry) => ({ ...entry, changes: entry.changes.map((change) => ({ ...change })), check: entry.check ? { ...entry.check } : undefined })) }
function clonePendingResult(result: GameSession['pendingResult']): GameSession['pendingResult'] { return result ? { ...result, changes: result.changes.map((change) => ({ ...change })) } : null }
function clonePendingAction(action: GameSession['pendingAction']): GameSession['pendingAction'] { return action ? { ...action, snapshot: { ...action.snapshot, stats: { ...action.snapshot.stats }, relationships: { ...action.snapshot.relationships }, tags: [...action.snapshot.tags], flags: { ...action.snapshot.flags } } } : null }
function convertLegacyIdentity(identity: LegacyLifeRecordV1['identity'] | LegacyGameSessionV1['state']['identity']): LegacyLifeRecordV2['identity'] { return { ...identity, birthDay: 0, talentIds: [...identity.talentIds] } }
function convertLegacyRecord(record: LegacyLifeRecordV1, activeAtMigration: boolean): LegacyLifeRecordV2 { return { sequence: record.sequence, runId: record.runId, runSeed: record.runSeed, stateDigest: record.stateDigest, identity: convertLegacyIdentity(record.identity), stats: { ...record.stats }, resources: { ...record.resources }, cultivation: { ...record.cultivation }, eventHistory: [...record.eventHistory], chronicle: [], summary: { ...record.summary }, debugLog: convertLegacyDebugLog(record.debugLog), legacy: { sourceSchemaVersion: 1, migrationReason: 'v2_schema_upgrade', activeAtMigration } } }
function cloneLegacyV2Record(record: LegacyLifeRecordV2): LegacyLifeRecordV2 { return { ...record, identity: { ...record.identity, talentIds: [...record.identity.talentIds] }, stats: { ...record.stats }, resources: { ...record.resources }, cultivation: { ...record.cultivation }, eventHistory: [...record.eventHistory], chronicle: cloneChronicle(record.chronicle), summary: { ...record.summary }, debugLog: cloneCurrentDebugLog(record.debugLog), legacy: record.legacy ? { ...record.legacy } : undefined } }
function cloneCurrentRecord(record: LifeRecord): LifeRecord { return { ...record, identity: { ...record.identity, physiqueIds: [...record.identity.physiqueIds], talentIds: [...record.identity.talentIds] }, stats: { ...record.stats }, resources: { ...record.resources }, cultivation: { ...record.cultivation }, eventHistory: [...record.eventHistory], chronicle: cloneChronicle(record.chronicle), summary: { ...record.summary }, debugLog: cloneCurrentDebugLog(record.debugLog), legacy: record.legacy ? { ...record.legacy } : undefined } }

export function upgradeGameStateV2ToV3(state: LegacyGameSessionV2['state']): GameState { return { ...state, schemaVersion: 3, lifeStage: 'legacy-adult', childhood: null, identity: { ...state.identity, physiqueIds: [], talentIds: [...state.identity.talentIds] }, stats: { ...state.stats }, resources: { ...state.resources }, cultivation: { ...state.cultivation }, world: { currentLocationId: null }, knowledge: { locations: {} }, tags: [...state.tags], flags: { ...state.flags }, relationships: { ...state.relationships }, events: { ...state.events, queue: [...state.events.queue], history: [...state.events.history] }, chronicle: cloneChronicle(state.chronicle) } }
function cloneCurrentSession(session: GameSession): GameSession { const childhood = session.state.childhood ? { ...session.state.childhood, nodeIds: [...session.state.childhood.nodeIds], completedNodeIds: [...session.state.childhood.completedNodeIds] } : null; return { state: { ...session.state, childhood, identity: { ...session.state.identity, physiqueIds: [...session.state.identity.physiqueIds], talentIds: [...session.state.identity.talentIds] }, stats: { ...session.state.stats }, resources: { ...session.state.resources }, cultivation: { ...session.state.cultivation }, world: { ...session.state.world }, knowledge: { locations: { ...session.state.knowledge.locations } }, tags: [...session.state.tags], flags: { ...session.state.flags }, relationships: { ...session.state.relationships }, events: { ...session.state.events, queue: [...session.state.events.queue], history: [...session.state.events.history] }, chronicle: cloneChronicle(session.state.chronicle) }, debugLog: cloneCurrentDebugLog(session.debugLog), pendingResult: clonePendingResult(session.pendingResult), pendingAction: clonePendingAction(session.pendingAction) } }
function upgradeV2SessionToV3(session: LegacyGameSessionV2): GameSession { return { state: upgradeGameStateV2ToV3(session.state), debugLog: cloneCurrentDebugLog(session.debugLog), pendingResult: clonePendingResult(session.pendingResult), pendingAction: clonePendingAction(session.pendingAction) } }
function upgradeV2RecordToV3(record: LegacyLifeRecordV2): LifeRecord { return { ...record, identity: { ...record.identity, physiqueIds: [], talentIds: [...record.identity.talentIds] }, stats: { ...record.stats }, resources: { ...record.resources }, cultivation: { ...record.cultivation }, eventHistory: [...record.eventHistory], chronicle: cloneChronicle(record.chronicle), summary: { ...record.summary }, debugLog: cloneCurrentDebugLog(record.debugLog), legacy: record.legacy ? { ...record.legacy } : undefined } }
function convertLegacySessionV1ToV2(session: LegacyGameSessionV1): LegacyGameSessionV2 { return { state: { schemaVersion: 2, runId: session.state.runId, runSeed: session.state.runSeed, rngState: session.state.rngState, status: session.state.status, worldDay: session.state.timeMonths * DAYS_PER_MONTH, identity: convertLegacyIdentity(session.state.identity), stats: { ...session.state.stats }, resources: { ...session.state.resources }, cultivation: { ...session.state.cultivation }, tags: [...session.state.tags], flags: { ...session.state.flags }, relationships: { ...session.state.relationships }, events: { ...session.state.events, queue: [...session.state.events.queue], history: [...session.state.events.history] }, chronicle: [], endReason: session.state.endReason }, debugLog: convertLegacyDebugLog(session.debugLog), pendingResult: clonePendingResult(session.pendingResult), pendingAction: null } }
function getLegacyLifeTitle(session: LegacyGameSessionV1): string { const { state } = session; if (state.cultivation.realm === 'golden_core') return '金丹真人（旧版存档）'; if (state.cultivation.realm === 'foundation') return '筑基修士（旧版存档）'; if (state.cultivation.realm === 'qi') return '炼气行者（旧版存档）'; return '凡尘一世（旧版存档）' }
function convertActiveLegacySessionToRecord(session: LegacyGameSessionV1, sequence: number): LegacyLifeRecordV2 { const ageMonths = Math.max(0, session.state.timeMonths); return { sequence, runId: session.state.runId, runSeed: session.state.runSeed, stateDigest: digestText(stableStringify(session.state)), identity: convertLegacyIdentity(session.state.identity), stats: { ...session.state.stats }, resources: { ...session.state.resources }, cultivation: { ...session.state.cultivation }, eventHistory: [...session.state.events.history], chronicle: [], summary: { title: getLegacyLifeTitle(session), finalRealm: session.state.cultivation.realm, ageYears: Math.floor(ageMonths / MONTHS_PER_YEAR), ageMonths: ageMonths % MONTHS_PER_YEAR, outcome: 'migrated', endReason: '旧版进行中人生已封存；V2.0 不会把它静默套入新世界规则。', largestOpportunity: '旧版进行中人生', regret: '未在旧版规则下继续结算' }, debugLog: convertLegacyDebugLog(session.debugLog), legacy: { sourceSchemaVersion: 1, migrationReason: 'v3_schema_upgrade', activeAtMigration: true } } }
function convertActiveLegacyV2SessionToRecord(session: LegacyGameSessionV2, sequence: number): LegacyLifeRecordV2 { const ageDays = Math.max(0, session.state.worldDay - session.state.identity.birthDay); return { sequence, runId: session.state.runId, runSeed: session.state.runSeed, stateDigest: digestText(stableStringify(session.state)), identity: { ...session.state.identity, talentIds: [...session.state.identity.talentIds] }, stats: { ...session.state.stats }, resources: { ...session.state.resources }, cultivation: { ...session.state.cultivation }, eventHistory: [...session.state.events.history], chronicle: cloneChronicle(session.state.chronicle), summary: { title: '旧版进行中人生（已封存）', finalRealm: session.state.cultivation.realm, ageYears: Math.floor(ageDays / DAYS_PER_YEAR), ageMonths: Math.floor((ageDays % DAYS_PER_YEAR) / DAYS_PER_MONTH), outcome: 'migrated', endReason: '旧版进行中人生已封存；V2.0 不会把它静默套入新世界规则。', largestOpportunity: '旧版进行中人生', regret: '未在旧版规则下继续结算' }, debugLog: cloneCurrentDebugLog(session.debugLog), legacy: { sourceSchemaVersion: 2, migrationReason: 'v3_schema_upgrade', activeAtMigration: true } } }
function normalizeV2(raw: TransitionalPersistentGameV2): NormalizedPersistentGameV2 { const currentSession = raw.currentSession ? ('timeMonths' in raw.currentSession.state ? convertLegacySessionV1ToV2(raw.currentSession) : raw.currentSession) : null; const archives = raw.archives.map((record) => 'timeMonthsBefore' in (record.debugLog[0] ?? {}) ? convertLegacyRecord(record as LegacyLifeRecordV1, false) : cloneLegacyV2Record(record as LegacyLifeRecordV2)); return { schemaVersion: 2, currentSession, archives, meta: { ...raw.meta } } }
export function migrateV2ToV3(raw: TransitionalPersistentGameV2): PersistentGame { const normalized = normalizeV2(raw); const archives = normalized.archives.map((record) => upgradeV2RecordToV3(record)); if (!normalized.currentSession) return { schemaVersion: 3, phase: 'birth-selection', currentSession: null, pendingBirthSelection: null, archives, meta: { ...normalized.meta } }; const current = normalized.currentSession; const activeRecord = convertActiveLegacyV2SessionToRecord(current, archives.length + 1); return { schemaVersion: 3, phase: 'birth-selection', currentSession: null, pendingBirthSelection: null, archives: [...archives, upgradeV2RecordToV3(activeRecord)], meta: { ...normalized.meta } } }
export function normalizeV3(raw: TransitionalPersistentGameV3): PersistentGame { const currentSession = raw.currentSession ? ('lifeStage' in raw.currentSession.state ? cloneCurrentSession(raw.currentSession as GameSession) : upgradeV2SessionToV3(raw.currentSession as LegacyGameSessionV2)) : null; const archives = raw.archives.map((record) => 'physiqueIds' in record.identity ? cloneCurrentRecord(record as LifeRecord) : upgradeV2RecordToV3(record as LegacyLifeRecordV2)); const pendingBirthSelection = raw.pendingBirthSelection ? { ...raw.pendingBirthSelection, candidates: raw.pendingBirthSelection.candidates.map((candidate) => ({ ...candidate, talentIds: [...candidate.talentIds], stats: { ...candidate.stats } })) } : null; return { schemaVersion: 3, phase: raw.phase, currentSession, pendingBirthSelection, archives, meta: { ...raw.meta } } }
export function migrateV1ToV2(raw: LegacyPersistentGameV1): NormalizedPersistentGameV2 { const currentSession = raw.currentSession ? convertLegacySessionV1ToV2(raw.currentSession) : null; const archives = raw.archives.map((record) => convertLegacyRecord(record, false)); return { schemaVersion: 2, currentSession, archives, meta: { ...raw.meta } } }
